stages:
  - Unit tests
  - Package build
  - Documentation

.install: &install
  before_script:
    - apt update -y && apt install -y git make
    - export UV_INDEX_URL="https://$ARTIFACTORY_TOKEN_NAME:$ARTIFACTORY_TOKEN@bmxrdartifactoryfr.jfrog.io/artifactory/api/pypi/bmx-pypi/simple"
    - pip install go-task-bin

image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim

test:
  <<: *install
  stage: Unit tests
  script:
    - task test

package:
  <<: *install
  stage: Package build
  script:
    - echo $CI_COMMIT_TAG > athletics_performance/VERSION
    - task publish
  only:
    - tags

pages:
  <<: *install
  stage: Documentation
  script:
    - echo $CI_COMMIT_TAG > athletics_performance/VERSION
    - task doc
    - mv docs/_build/html/ public/
    - PAGES_URL="https://${CI_PROJECT_ROOT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAMESPACE#${CI_PROJECT_ROOT_NAMESPACE}/}/${CI_PROJECT_NAME}"
    - echo "Documentation is available here $PAGES_URL"
  only:
    - tags
  artifacts:
    paths:
    - public
